export const CHANGE_SEARCHFIELD = 'CHANGE_SEARCHFIELD';

export const SET_IMAGE_URL = 'SET_IMAGE_URL';

export const REQUEST_FACE_DETECTION_PENDING = 'REQUEST_FACE_DETECTION_PENDING';
export const REQUEST_FACE_DETECTION_SUCCESS = 'REQUEST_FACE_DETECTION_SUCCESS';
export const REQUEST_FACE_DETECTION_FAILED = 'REQUEST_FACE_DETECTION_FAILED';

export const GET_PROFILE = 'GET_PROFILE';

export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';